part of 'iris_item_repository.dart';

const int irisBeautyFashionItemCount = 138;

String _expandedWeightClass(double weightKg) {
  if (weightKg <= 2) return 'Small Parcel';
  if (weightKg <= 10) return 'Medium Parcel';
  if (weightKg <= 25) return 'Large Parcel';
  if (weightKg <= 50) return 'Heavy Goods';
  return 'Heavy Duty Freight';
}

String _expandedSizeClass(double maximumWeightKg) {
  if (maximumWeightKg <= 2) return 'small';
  if (maximumWeightKg <= 10) return 'medium';
  return 'large';
}

IrisRepositoryItem _expandedIrisItem({
  required String id,
  required String itemName,
  required List<String> aliases,
  required String category,
  required String subcategory,
  required double estimated,
  required double minimum,
  required double maximum,
  required bool fragile,
  required bool highValue,
  required bool requiresVanguard,
  required bool requiresReview,
  required List<String> giftSignals,
}) {
  return IrisRepositoryItem(
    id: id,
    itemName: itemName,
    aliases: aliases,
    category: category,
    subcategory: subcategory,
    estimatedWeightKg: estimated,
    minimumWeightKg: minimum,
    maximumWeightKg: maximum,
    weightClass: _expandedWeightClass(estimated),
    sizeClass: _expandedSizeClass(maximum),
    fragile: fragile,
    highValue: highValue,
    requiresVanguard: requiresVanguard,
    requiresIRISReview: requiresReview,
    deliveryNotes:
        '$subcategory item. Keep securely packaged and protect from moisture or impact where appropriate.',
    confidenceBaseline: 0.86,
    typicalDimensionsCm: const IrisRepositoryDimensions(
      lengthCm: 40,
      widthCm: 30,
      heightCm: 20,
    ),
    vehicleSuitability: 'Car',
    stackable: category != 'Gifts',
    giftSignals: giftSignals.toSet(),
    allowedVehicles: const ['Bike', 'Car'],
    requiresVan: false,
    confidenceBoostTerms: aliases,
  );
}

final List<IrisRepositoryItem> irisBeautyFashionItems = List.unmodifiable([
  _expandedIrisItem(
      id: "beauty_fashion_001_lipstick",
      itemName: "Lipstick",
      aliases: const ["lipstick", "lip stick"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.03,
      minimum: 0.02,
      maximum: 0.05,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_002_lip_gloss",
      itemName: "Lip Gloss",
      aliases: const ["lip gloss", "lipgloss"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.04,
      minimum: 0.03,
      maximum: 0.08,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_003_foundation",
      itemName: "Foundation",
      aliases: const ["foundation"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.15,
      minimum: 0.1,
      maximum: 0.25,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_004_concealer",
      itemName: "Concealer",
      aliases: const ["concealer"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.05,
      minimum: 0.03,
      maximum: 0.1,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_005_face_powder",
      itemName: "Face Powder",
      aliases: const ["face powder"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.12,
      minimum: 0.08,
      maximum: 0.2,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_006_blush_palette",
      itemName: "Blush Palette",
      aliases: const ["blush palette"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.15,
      minimum: 0.1,
      maximum: 0.25,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_007_eyeshadow_palette",
      itemName: "Eyeshadow Palette",
      aliases: const ["eyeshadow palette"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.25,
      minimum: 0.15,
      maximum: 0.4,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_008_mascara",
      itemName: "Mascara",
      aliases: const ["mascara"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.05,
      minimum: 0.03,
      maximum: 0.1,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_009_eyeliner",
      itemName: "Eyeliner",
      aliases: const ["eyeliner"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.02,
      minimum: 0.01,
      maximum: 0.05,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_010_brow_pencil",
      itemName: "Brow Pencil",
      aliases: const ["brow pencil"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.02,
      minimum: 0.01,
      maximum: 0.05,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_011_makeup_brush_set",
      itemName: "Makeup Brush Set",
      aliases: const ["makeup brush set"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.35,
      minimum: 0.2,
      maximum: 0.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_012_beauty_blender_set",
      itemName: "Beauty Blender Set",
      aliases: const ["beauty blender set"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.1,
      minimum: 0.05,
      maximum: 0.25,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_013_makeup_bag",
      itemName: "Makeup Bag",
      aliases: const ["makeup bag"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 0.3,
      minimum: 0.15,
      maximum: 0.8,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_014_beauty_gift_set",
      itemName: "Beauty Gift Set",
      aliases: const ["beauty gift set", "makeup gift set"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 1.2,
      minimum: 0.5,
      maximum: 3,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_015_skincare_set",
      itemName: "Skincare Set",
      aliases: const ["skincare set"],
      category: "Beauty",
      subcategory: "Skincare",
      estimated: 1.5,
      minimum: 0.5,
      maximum: 4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "skincareInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_016_face_serum",
      itemName: "Face Serum",
      aliases: const ["face serum"],
      category: "Beauty",
      subcategory: "Skincare",
      estimated: 0.15,
      minimum: 0.1,
      maximum: 0.25,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "skincareInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_017_moisturiser",
      itemName: "Moisturiser",
      aliases: const ["moisturiser", "moisturizer"],
      category: "Beauty",
      subcategory: "Skincare",
      estimated: 0.2,
      minimum: 0.15,
      maximum: 0.4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "skincareInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_018_cleanser",
      itemName: "Cleanser",
      aliases: const ["cleanser"],
      category: "Beauty",
      subcategory: "Skincare",
      estimated: 0.25,
      minimum: 0.15,
      maximum: 0.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "skincareInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_019_toner",
      itemName: "Toner",
      aliases: const ["toner"],
      category: "Beauty",
      subcategory: "Skincare",
      estimated: 0.3,
      minimum: 0.15,
      maximum: 0.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "skincareInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_020_sunscreen",
      itemName: "Sunscreen",
      aliases: const ["sunscreen", "sun cream"],
      category: "Beauty",
      subcategory: "Skincare",
      estimated: 0.2,
      minimum: 0.1,
      maximum: 0.4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "skincareInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_021_body_lotion",
      itemName: "Body Lotion",
      aliases: const ["body lotion"],
      category: "Beauty",
      subcategory: "Body Care",
      estimated: 0.5,
      minimum: 0.25,
      maximum: 1,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_022_body_butter",
      itemName: "Body Butter",
      aliases: const ["body butter"],
      category: "Beauty",
      subcategory: "Body Care",
      estimated: 0.4,
      minimum: 0.2,
      maximum: 0.8,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_023_bath_bomb_set",
      itemName: "Bath Bomb Set",
      aliases: const ["bath bomb set", "bath bombs"],
      category: "Beauty",
      subcategory: "Body Care",
      estimated: 1,
      minimum: 0.4,
      maximum: 3,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_024_nail_polish",
      itemName: "Nail Polish",
      aliases: const ["nail polish", "nail varnish"],
      category: "Beauty",
      subcategory: "Nail Care",
      estimated: 0.06,
      minimum: 0.03,
      maximum: 0.12,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_025_nail_kit",
      itemName: "Nail Kit",
      aliases: const ["nail kit"],
      category: "Beauty",
      subcategory: "Nail Care",
      estimated: 0.5,
      minimum: 0.2,
      maximum: 1.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "selfCareInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_026_perfume_30ml",
      itemName: "Perfume 30ml",
      aliases: const ["perfume 30ml", "30ml perfume", "fragrance 30ml"],
      category: "Beauty",
      subcategory: "Fragrance",
      estimated: 0.2,
      minimum: 0.15,
      maximum: 0.3,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "fragranceInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_027_perfume_50ml",
      itemName: "Perfume 50ml",
      aliases: const ["perfume 50ml", "50ml perfume", "fragrance 50ml"],
      category: "Beauty",
      subcategory: "Fragrance",
      estimated: 0.3,
      minimum: 0.2,
      maximum: 0.45,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "fragranceInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_028_perfume_100ml",
      itemName: "Perfume 100ml",
      aliases: const ["perfume 100ml", "100ml perfume", "fragrance 100ml"],
      category: "Beauty",
      subcategory: "Fragrance",
      estimated: 0.5,
      minimum: 0.3,
      maximum: 0.7,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "fragranceInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_029_luxury_perfume_gift_box",
      itemName: "Luxury Perfume Gift Box",
      aliases: const ["luxury perfume gift box", "luxury fragrance gift"],
      category: "Beauty",
      subcategory: "Fragrance",
      estimated: 1,
      minimum: 0.5,
      maximum: 2,
      fragile: true,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "beautyInterest",
        "fragranceInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_030_body_mist",
      itemName: "Body Mist",
      aliases: const ["body mist", "body spray"],
      category: "Beauty",
      subcategory: "Fragrance",
      estimated: 0.3,
      minimum: 0.15,
      maximum: 0.6,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "fragranceInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_031_fragrance_set",
      itemName: "Fragrance Set",
      aliases: const ["fragrance set", "perfume set"],
      category: "Beauty",
      subcategory: "Fragrance",
      estimated: 1.2,
      minimum: 0.5,
      maximum: 2.5,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "beautyInterest",
        "fragranceInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_032_women_s_t_shirt",
      itemName: "Women's T-Shirt",
      aliases: const ["womens t-shirt", "womens tshirt", "ladies t shirt"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.2,
      minimum: 0.15,
      maximum: 0.4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_033_women_s_blouse",
      itemName: "Women's Blouse",
      aliases: const ["womens blouse"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.25,
      minimum: 0.15,
      maximum: 0.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_034_women_s_shirt",
      itemName: "Women's Shirt",
      aliases: const ["womens shirt"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.25,
      minimum: 0.15,
      maximum: 0.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_035_women_s_dress",
      itemName: "Women's Dress",
      aliases: const ["womens dress", "dress"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.6,
      minimum: 0.3,
      maximum: 1.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_036_evening_dress",
      itemName: "Evening Dress",
      aliases: const ["evening dress"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 1.5,
      minimum: 0.5,
      maximum: 4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_037_wedding_guest_dress",
      itemName: "Wedding Guest Dress",
      aliases: const ["wedding guest dress"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 1.2,
      minimum: 0.5,
      maximum: 3,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_038_women_s_jeans",
      itemName: "Women's Jeans",
      aliases: const ["womens jeans"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.7,
      minimum: 0.5,
      maximum: 1.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_039_leggings",
      itemName: "Leggings",
      aliases: const ["leggings"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.25,
      minimum: 0.15,
      maximum: 0.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_040_women_s_hoodie",
      itemName: "Women's Hoodie",
      aliases: const ["womens hoodie"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.8,
      minimum: 0.5,
      maximum: 1.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_041_women_s_jumper",
      itemName: "Women's Jumper",
      aliases: const ["womens jumper"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.6,
      minimum: 0.3,
      maximum: 1.2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_042_women_s_coat",
      itemName: "Women's Coat",
      aliases: const ["womens coat"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 2,
      minimum: 1,
      maximum: 5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_043_trench_coat",
      itemName: "Trench Coat",
      aliases: const ["trench coat"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 1.5,
      minimum: 0.8,
      maximum: 4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_044_women_s_suit",
      itemName: "Women's Suit",
      aliases: const ["womens suit"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 1.5,
      minimum: 0.8,
      maximum: 3.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_045_pyjama_set",
      itemName: "Pyjama Set",
      aliases: const ["pyjama set"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.5,
      minimum: 0.25,
      maximum: 1.2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_046_lingerie_set",
      itemName: "Lingerie Set",
      aliases: const ["lingerie set"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.15,
      minimum: 0.05,
      maximum: 0.4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_047_silk_robe",
      itemName: "Silk Robe",
      aliases: const ["silk robe"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.6,
      minimum: 0.3,
      maximum: 1.2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_048_cashmere_scarf",
      itemName: "Cashmere Scarf",
      aliases: const ["cashmere scarf"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.3,
      minimum: 0.15,
      maximum: 0.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_049_designer_belt",
      itemName: "Designer Belt",
      aliases: const ["designer belt"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.4,
      minimum: 0.2,
      maximum: 0.8,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable",
        "luxuryInterest"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_050_abaya",
      itemName: "Abaya",
      aliases: const ["abaya", "modest dress"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.8,
      minimum: 0.4,
      maximum: 1.8,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable",
        "modestFashionInterest"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_051_headscarf",
      itemName: "Headscarf",
      aliases: const ["headscarf", "hijab", "head scarf"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 0.2,
      minimum: 0.1,
      maximum: 0.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "clothingSizeRelevant",
        "fullBodyPhotoHelpful",
        "occasionGiftSuitable",
        "modestFashionInterest"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_052_trainers",
      itemName: "Trainers",
      aliases: const ["trainers", "sneakers"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 1,
      minimum: 0.6,
      maximum: 2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "footwearInterest",
        "clothingSizeRelevant",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_053_running_shoes",
      itemName: "Running Shoes",
      aliases: const ["running shoes", "running trainers"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 0.9,
      minimum: 0.5,
      maximum: 1.8,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "footwearInterest",
        "clothingSizeRelevant",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_054_designer_trainers",
      itemName: "Designer Trainers",
      aliases: const ["designer trainers"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 1.2,
      minimum: 0.7,
      maximum: 2.5,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "footwearInterest",
        "clothingSizeRelevant",
        "occasionGiftSuitable",
        "luxuryInterest"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_055_heels",
      itemName: "Heels",
      aliases: const ["heels"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 1,
      minimum: 0.6,
      maximum: 2.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "footwearInterest",
        "clothingSizeRelevant",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_056_designer_heels",
      itemName: "Designer Heels",
      aliases: const ["designer heels"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 1.2,
      minimum: 0.7,
      maximum: 3,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "footwearInterest",
        "clothingSizeRelevant",
        "occasionGiftSuitable",
        "luxuryInterest"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_057_boots",
      itemName: "Boots",
      aliases: const ["boots"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 1.8,
      minimum: 1,
      maximum: 4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "footwearInterest",
        "clothingSizeRelevant",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_058_sandals",
      itemName: "Sandals",
      aliases: const ["sandals"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 0.6,
      minimum: 0.3,
      maximum: 1.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "footwearInterest",
        "clothingSizeRelevant",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_059_slippers",
      itemName: "Slippers",
      aliases: const ["slippers"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 0.4,
      minimum: 0.2,
      maximum: 1,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "footwearInterest",
        "clothingSizeRelevant",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_060_women_s_shoe_box",
      itemName: "Women's Shoe Box",
      aliases: const ["womens shoe box", "womens shoes", "shoe box"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 1.2,
      minimum: 0.6,
      maximum: 3,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "footwearInterest",
        "clothingSizeRelevant",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_061_handbag",
      itemName: "Handbag",
      aliases: const ["handbag"],
      category: "Fashion",
      subcategory: "Handbags",
      estimated: 1,
      minimum: 0.5,
      maximum: 3,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["fashionInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_062_designer_handbag",
      itemName: "Designer Handbag",
      aliases: const ["designer handbag", "designer bag", "luxury handbag"],
      category: "Fashion",
      subcategory: "Handbags",
      estimated: 1.5,
      minimum: 0.8,
      maximum: 4,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "fashionInterest",
        "occasionGiftSuitable",
        "luxuryInterest"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_063_tote_bag",
      itemName: "Tote Bag",
      aliases: const ["tote bag"],
      category: "Fashion",
      subcategory: "Handbags",
      estimated: 0.8,
      minimum: 0.4,
      maximum: 2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["fashionInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_064_clutch_bag",
      itemName: "Clutch Bag",
      aliases: const ["clutch bag", "clutch"],
      category: "Fashion",
      subcategory: "Handbags",
      estimated: 0.4,
      minimum: 0.2,
      maximum: 1,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["fashionInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_065_purse",
      itemName: "Purse",
      aliases: const ["purse"],
      category: "Fashion",
      subcategory: "Handbags",
      estimated: 0.25,
      minimum: 0.1,
      maximum: 0.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["fashionInterest", "occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_066_jewellery_box",
      itemName: "Jewellery Box",
      aliases: const ["jewellery box", "jewelry box"],
      category: "Fashion",
      subcategory: "Jewellery & Accessories",
      estimated: 0.5,
      minimum: 0.2,
      maximum: 1.5,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: true,
      giftSignals: const [
        "fashionInterest",
        "jewelleryInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_067_gold_necklace",
      itemName: "Gold Necklace",
      aliases: const ["gold necklace", "gold chain", "necklace"],
      category: "Fashion",
      subcategory: "Jewellery & Accessories",
      estimated: 0.1,
      minimum: 0.05,
      maximum: 0.3,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "fashionInterest",
        "jewelleryInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_068_bracelet",
      itemName: "Bracelet",
      aliases: const ["bracelet"],
      category: "Fashion",
      subcategory: "Jewellery & Accessories",
      estimated: 0.05,
      minimum: 0.02,
      maximum: 0.15,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "fashionInterest",
        "jewelleryInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_069_earrings",
      itemName: "Earrings",
      aliases: const ["earrings", "ear rings"],
      category: "Fashion",
      subcategory: "Jewellery & Accessories",
      estimated: 0.02,
      minimum: 0.01,
      maximum: 0.08,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "fashionInterest",
        "jewelleryInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_070_ring_box",
      itemName: "Ring Box",
      aliases: const ["ring box"],
      category: "Fashion",
      subcategory: "Jewellery & Accessories",
      estimated: 0.05,
      minimum: 0.02,
      maximum: 0.15,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "fashionInterest",
        "jewelleryInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_071_luxury_watch",
      itemName: "Luxury Watch",
      aliases: const ["luxury watch", "designer watch"],
      category: "Fashion",
      subcategory: "Jewellery & Accessories",
      estimated: 0.15,
      minimum: 0.1,
      maximum: 0.3,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "fashionInterest",
        "jewelleryInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_072_designer_sunglasses",
      itemName: "Designer Sunglasses",
      aliases: const ["designer sunglasses", "designer shades"],
      category: "Fashion",
      subcategory: "Jewellery & Accessories",
      estimated: 0.2,
      minimum: 0.1,
      maximum: 0.5,
      fragile: true,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "fashionInterest",
        "jewelleryInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_073_hair_clip_set",
      itemName: "Hair Clip Set",
      aliases: const ["hair clip set"],
      category: "Fashion",
      subcategory: "Jewellery & Accessories",
      estimated: 0.15,
      minimum: 0.05,
      maximum: 0.4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "fashionInterest",
        "jewelleryInterest",
        "luxuryInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_074_synthetic_wig",
      itemName: "Synthetic Wig",
      aliases: const ["synthetic wig", "wig unit"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.3,
      minimum: 0.15,
      maximum: 0.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_075_short_synthetic_wig",
      itemName: "Short Synthetic Wig",
      aliases: const ["short synthetic wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.25,
      minimum: 0.1,
      maximum: 0.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_076_long_synthetic_wig",
      itemName: "Long Synthetic Wig",
      aliases: const ["long synthetic wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.5,
      minimum: 0.2,
      maximum: 1,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_077_curly_synthetic_wig",
      itemName: "Curly Synthetic Wig",
      aliases: const ["curly synthetic wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.45,
      minimum: 0.2,
      maximum: 0.9,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_078_lace_front_synthetic_wig",
      itemName: "Lace Front Synthetic Wig",
      aliases: const ["lace front synthetic wig", "lace front wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.6,
      minimum: 0.3,
      maximum: 1.2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_079_human_hair_wig",
      itemName: "Human Hair Wig",
      aliases: const ["human hair wig", "human hair"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.5,
      minimum: 0.2,
      maximum: 1.2,
      fragile: false,
      highValue: true,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_080_brazilian_human_hair_wig",
      itemName: "Brazilian Human Hair Wig",
      aliases: const ["brazilian human hair wig", "brazilian hair"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.7,
      minimum: 0.3,
      maximum: 1.5,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_081_peruvian_human_hair_wig",
      itemName: "Peruvian Human Hair Wig",
      aliases: const ["peruvian human hair wig", "peruvian hair"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.7,
      minimum: 0.3,
      maximum: 1.5,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_082_malaysian_human_hair_wig",
      itemName: "Malaysian Human Hair Wig",
      aliases: const ["malaysian human hair wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.7,
      minimum: 0.3,
      maximum: 1.5,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_083_indian_human_hair_wig",
      itemName: "Indian Human Hair Wig",
      aliases: const ["indian human hair wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.7,
      minimum: 0.3,
      maximum: 1.5,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_084_straight_human_hair_wig",
      itemName: "Straight Human Hair Wig",
      aliases: const ["straight human hair wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.6,
      minimum: 0.25,
      maximum: 1.2,
      fragile: false,
      highValue: true,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_085_curly_human_hair_wig",
      itemName: "Curly Human Hair Wig",
      aliases: const ["curly human hair wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.8,
      minimum: 0.3,
      maximum: 1.8,
      fragile: false,
      highValue: true,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_086_deep_wave_wig",
      itemName: "Deep Wave Wig",
      aliases: const ["deep wave wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.9,
      minimum: 0.4,
      maximum: 2,
      fragile: false,
      highValue: true,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_087_water_wave_wig",
      itemName: "Water Wave Wig",
      aliases: const ["water wave wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.9,
      minimum: 0.4,
      maximum: 2,
      fragile: false,
      highValue: true,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_088_body_wave_wig",
      itemName: "Body Wave Wig",
      aliases: const ["body wave wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.8,
      minimum: 0.3,
      maximum: 1.8,
      fragile: false,
      highValue: true,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_089_hd_lace_wig",
      itemName: "HD Lace Wig",
      aliases: const ["hd lace wig", "hd lace"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.8,
      minimum: 0.3,
      maximum: 1.8,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_090_frontal_wig",
      itemName: "Frontal Wig",
      aliases: const ["frontal wig", "frontal"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.7,
      minimum: 0.3,
      maximum: 1.5,
      fragile: false,
      highValue: true,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_091_closure_wig",
      itemName: "Closure Wig",
      aliases: const ["closure wig", "closure"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.6,
      minimum: 0.25,
      maximum: 1.2,
      fragile: false,
      highValue: true,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_092_bob_wig",
      itemName: "Bob Wig",
      aliases: const ["bob wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.5,
      minimum: 0.2,
      maximum: 1,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_093_pixie_wig",
      itemName: "Pixie Wig",
      aliases: const ["pixie wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.3,
      minimum: 0.15,
      maximum: 0.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_094_8_inch_wig",
      itemName: "8 Inch Wig",
      aliases: const ["8 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.3,
      minimum: 0.15,
      maximum: 0.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_095_10_inch_wig",
      itemName: "10 Inch Wig",
      aliases: const ["10 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.4,
      minimum: 0.2,
      maximum: 0.7,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_096_12_inch_wig",
      itemName: "12 Inch Wig",
      aliases: const ["12 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.5,
      minimum: 0.25,
      maximum: 0.9,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_097_14_inch_wig",
      itemName: "14 Inch Wig",
      aliases: const ["14 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.6,
      minimum: 0.3,
      maximum: 1,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_098_16_inch_wig",
      itemName: "16 Inch Wig",
      aliases: const ["16 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.7,
      minimum: 0.35,
      maximum: 1.2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_099_18_inch_wig",
      itemName: "18 Inch Wig",
      aliases: const ["18 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.8,
      minimum: 0.4,
      maximum: 1.4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_100_20_inch_wig",
      itemName: "20 Inch Wig",
      aliases: const ["20 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.9,
      minimum: 0.45,
      maximum: 1.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_101_22_inch_wig",
      itemName: "22 Inch Wig",
      aliases: const ["22 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 1,
      minimum: 0.5,
      maximum: 1.8,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_102_24_inch_wig",
      itemName: "24 Inch Wig",
      aliases: const ["24 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 1.1,
      minimum: 0.55,
      maximum: 2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_103_26_inch_wig",
      itemName: "26 Inch Wig",
      aliases: const ["26 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 1.2,
      minimum: 0.6,
      maximum: 2.2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_104_28_inch_wig",
      itemName: "28 Inch Wig",
      aliases: const ["28 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 1.3,
      minimum: 0.65,
      maximum: 2.4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_105_30_inch_wig",
      itemName: "30 Inch Wig",
      aliases: const ["30 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 1.4,
      minimum: 0.7,
      maximum: 2.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_106_32_inch_wig",
      itemName: "32 Inch Wig",
      aliases: const ["32 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 1.5,
      minimum: 0.8,
      maximum: 2.8,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_107_34_inch_wig",
      itemName: "34 Inch Wig",
      aliases: const ["34 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 1.7,
      minimum: 0.9,
      maximum: 3,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_108_36_inch_wig",
      itemName: "36 Inch Wig",
      aliases: const ["36 inch wig"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 2,
      minimum: 1,
      maximum: 3.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_109_luxury_human_hair_wig",
      itemName: "Luxury Human Hair Wig",
      aliases: const [
        "luxury human hair wig",
        "premium wig",
        "luxury wig over £500"
      ],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 1.2,
      minimum: 0.5,
      maximum: 2.5,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable",
        "luxuryInterest"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_110_clip_in_extensions",
      itemName: "Clip-In Extensions",
      aliases: const ["clip-in extensions", "clip in hair extensions"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 0.3,
      minimum: 0.15,
      maximum: 0.7,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_111_tape_in_extensions",
      itemName: "Tape-In Extensions",
      aliases: const ["tape-in extensions", "tape in hair extensions"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 0.4,
      minimum: 0.2,
      maximum: 0.8,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_112_sew_in_bundles",
      itemName: "Sew-In Bundles",
      aliases: const ["sew-in bundles", "weave bundles"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 0.5,
      minimum: 0.25,
      maximum: 1,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_113_single_bundle_hair",
      itemName: "Single Bundle Hair",
      aliases: const ["single bundle hair", "hair bundle"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 0.25,
      minimum: 0.1,
      maximum: 0.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_114_three_bundle_set",
      itemName: "Three Bundle Set",
      aliases: const ["three bundle set", "3 bundles"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 0.75,
      minimum: 0.4,
      maximum: 1.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_115_four_bundle_set",
      itemName: "Four Bundle Set",
      aliases: const ["four bundle set", "4 bundles"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 1,
      minimum: 0.5,
      maximum: 2,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_116_ponytail_extension",
      itemName: "Ponytail Extension",
      aliases: const ["ponytail extension"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 0.2,
      minimum: 0.1,
      maximum: 0.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_117_braiding_hair_pack",
      itemName: "Braiding Hair Pack",
      aliases: const ["braiding hair pack"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 0.25,
      minimum: 0.1,
      maximum: 0.6,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_118_crochet_hair_pack",
      itemName: "Crochet Hair Pack",
      aliases: const ["crochet hair pack"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 0.2,
      minimum: 0.1,
      maximum: 0.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_119_luxury_hair_extension_set",
      itemName: "Luxury Hair Extension Set",
      aliases: const ["luxury hair extension set", "luxury extensions"],
      category: "Wigs & Hair",
      subcategory: "Hair Extensions",
      estimated: 1.2,
      minimum: 0.6,
      maximum: 2.5,
      fragile: false,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const [
        "hairInterest",
        "beautyInterest",
        "occasionGiftSuitable",
        "luxuryInterest"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_120_flower_bouquet",
      itemName: "Flower Bouquet",
      aliases: const ["flower bouquet", "flowers", "bouquet"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 1,
      minimum: 0.5,
      maximum: 3,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["occasionGiftSuitable", "selfCareInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_121_luxury_flower_arrangement",
      itemName: "Luxury Flower Arrangement",
      aliases: const ["luxury flower arrangement", "luxury flowers"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 3,
      minimum: 1,
      maximum: 8,
      fragile: true,
      highValue: true,
      requiresVanguard: false,
      requiresReview: true,
      giftSignals: const ["occasionGiftSuitable", "luxuryInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_122_chocolate_gift_box",
      itemName: "Chocolate Gift Box",
      aliases: const ["chocolate gift box"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 1,
      minimum: 0.3,
      maximum: 3,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["occasionGiftSuitable", "selfCareInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_123_gift_hamper",
      itemName: "Gift Hamper",
      aliases: const ["gift hamper", "hamper"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 7,
      minimum: 2,
      maximum: 20,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: true,
      giftSignals: const ["occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_124_spa_hamper",
      itemName: "Spa Hamper",
      aliases: const ["spa hamper", "spa gift hamper"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 5,
      minimum: 2,
      maximum: 15,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: true,
      giftSignals: const [
        "occasionGiftSuitable",
        "selfCareInterest",
        "beautyInterest"
      ]),
  _expandedIrisItem(
      id: "beauty_fashion_125_beauty_hamper",
      itemName: "Beauty Hamper",
      aliases: const ["beauty hamper", "beauty gift hamper"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 6,
      minimum: 2,
      maximum: 20,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: true,
      giftSignals: const ["occasionGiftSuitable", "beautyInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_126_self_care_package",
      itemName: "Self Care Package",
      aliases: const ["self care package", "self care gift"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 4,
      minimum: 1,
      maximum: 10,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["occasionGiftSuitable", "selfCareInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_127_luxury_gift_box",
      itemName: "Luxury Gift Box",
      aliases: const ["luxury gift box"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 5,
      minimum: 2,
      maximum: 15,
      fragile: true,
      highValue: true,
      requiresVanguard: true,
      requiresReview: true,
      giftSignals: const ["occasionGiftSuitable", "luxuryInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_128_birthday_gift_bundle",
      itemName: "Birthday Gift Bundle",
      aliases: const ["birthday gift bundle"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 5,
      minimum: 2,
      maximum: 20,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: true,
      giftSignals: const ["occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_129_valentine_s_gift_bundle",
      itemName: "Valentine's Gift Bundle",
      aliases: const [
        "valentines gift bundle",
        "valentine's gift bundle",
        "valentines gift"
      ],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 4,
      minimum: 1,
      maximum: 15,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: true,
      giftSignals: const ["occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_130_mother_s_day_gift_bundle",
      itemName: "Mother's Day Gift Bundle",
      aliases: const [
        "mothers day gift bundle",
        "mother's day gift bundle",
        "mothers day gift"
      ],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 5,
      minimum: 2,
      maximum: 20,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: true,
      giftSignals: const ["occasionGiftSuitable"]),
  _expandedIrisItem(
      id: "beauty_fashion_131_graduation_beauty_gift",
      itemName: "Graduation Beauty Gift",
      aliases: const ["graduation beauty gift"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 3,
      minimum: 1,
      maximum: 10,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["occasionGiftSuitable", "beautyInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_132_bridal_beauty_package",
      itemName: "Bridal Beauty Package",
      aliases: const ["bridal beauty package"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 4,
      minimum: 1,
      maximum: 15,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: true,
      giftSignals: const ["occasionGiftSuitable", "beautyInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_133_salon_gift_package",
      itemName: "Salon Gift Package",
      aliases: const ["salon gift package"],
      category: "Gifts",
      subcategory: "Beauty & Lifestyle Gifts",
      estimated: 4,
      minimum: 1,
      maximum: 12,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["occasionGiftSuitable", "beautyInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_134_generic_wig",
      itemName: "Wig",
      aliases: const ["wig", "wigs", "wig unit"],
      category: "Wigs & Hair",
      subcategory: "Wigs",
      estimated: 0.7,
      minimum: 0.3,
      maximum: 1.5,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["hairInterest", "beautyInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_135_makeup_kit",
      itemName: "Makeup Kit",
      aliases: const ["makeup kit", "makeup box", "cosmetics kit"],
      category: "Beauty",
      subcategory: "Makeup",
      estimated: 4,
      minimum: 2,
      maximum: 8,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_136_skincare_box",
      itemName: "Skincare Box",
      aliases: const ["skincare box", "skin care box"],
      category: "Beauty",
      subcategory: "Skincare",
      estimated: 2,
      minimum: 0.5,
      maximum: 4,
      fragile: true,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["beautyInterest", "skincareInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_137_shoes",
      itemName: "Shoes",
      aliases: const ["shoes", "pair of shoes", "womens shoes"],
      category: "Fashion",
      subcategory: "Footwear",
      estimated: 1.5,
      minimum: 1,
      maximum: 4,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["fashionInterest", "footwearInterest"]),
  _expandedIrisItem(
      id: "beauty_fashion_138_clothing_bag",
      itemName: "Clothing Bag",
      aliases: const ["clothing bag", "clothes bag", "bag of clothes"],
      category: "Fashion",
      subcategory: "Womenswear",
      estimated: 4,
      minimum: 1,
      maximum: 8,
      fragile: false,
      highValue: false,
      requiresVanguard: false,
      requiresReview: false,
      giftSignals: const ["fashionInterest"]),
]);
