import 'design_status.dart';

const senderScreenRegistry = <DesignScreenRecord>[
  DesignScreenRecord(
    id: 'SEN-001',
    name: 'Home',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.deployed,
    stateIds: ['FIN-001-ST-02'],
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-002',
    name: 'Pickup',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-003',
    name: 'Drop-off',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-004',
    name: 'Recipient',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-005',
    name: 'Delivery Time',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-006',
    name: 'Parcel',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-007',
    name: 'IRIS',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-008',
    name: 'Delivery Options',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-009',
    name: 'Review',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-010',
    name: 'Payment',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-011',
    name: 'Finding Rider',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-012',
    name: 'Live Tracking',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.deployed,
    stateIds: [
      'SEN-012-ST-01',
      'SEN-012-ST-02',
      'SEN-012-ST-03',
      'SEN-012-ST-04',
      'SEN-012-ST-05',
      'SEN-012-ST-06',
      'SEN-012-ST-07',
      'SEN-012-ST-08',
      'SEN-012-ST-09',
      'SEN-012-ST-10',
      'SEN-012-ST-11',
    ],
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-013',
    name: 'Activity',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-014',
    name: 'Wallet',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.deployed,
    stateIds: [
      'FIN-001-ST-01',
      'FIN-001-ST-02',
      'FIN-001-ST-03',
      'FIN-001-ST-04',
      'FIN-001-ST-05',
      'FIN-001-ST-06',
    ],
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'SEN-015',
    name: 'Profile',
    product: DesignInventoryProduct.sender,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
];

const riderScreenRegistry = <DesignScreenRecord>[
  DesignScreenRecord(
    id: 'RID-001',
    name: 'Home',
    product: DesignInventoryProduct.rider,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'RID-002',
    name: 'Offers',
    product: DesignInventoryProduct.rider,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'RID-003',
    name: 'Navigation',
    product: DesignInventoryProduct.rider,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'RID-004',
    name: 'Pickup Verification',
    product: DesignInventoryProduct.rider,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'RID-005',
    name: 'Active Delivery',
    product: DesignInventoryProduct.rider,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'RID-006',
    name: 'Earnings',
    product: DesignInventoryProduct.rider,
    status: DesignInventoryStatus.uiPending,
    backend: DesignInventoryStatus.backendOnly,
    ui: DesignInventoryStatus.uiPending,
    deployment: DesignInventoryStatus.uiPending,
    missingWork: ['Rider Earnings UI', 'deployment'],
  ),
  DesignScreenRecord(
    id: 'RID-007',
    name: 'Profile',
    product: DesignInventoryProduct.rider,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
];

const healthScreenRegistry = <DesignScreenRecord>[
  DesignScreenRecord(
    id: 'HLT-001',
    name: 'Your Care',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    stateIds: [
      'HLT-001-ST-01',
      'HLT-001-ST-02',
      'HLT-001-ST-03',
      'HLT-001-ST-04',
      'HLT-001-ST-05',
      'HLT-001-ST-06',
      'HLT-001-ST-07',
    ],
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'HLT-002',
    name: 'Details',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'HLT-003',
    name: 'Pharmacy',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'HLT-004',
    name: 'Delivery',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'HLT-005',
    name: 'Frequency',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'HLT-006',
    name: 'Plan',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'HLT-007',
    name: 'Notes',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'HLT-008',
    name: 'Review',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'HLT-009',
    name: 'Checkout',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'HLT-010',
    name: 'Confirmation',
    product: DesignInventoryProduct.health,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
];

const giftsScreenRegistry = <DesignScreenRecord>[
  DesignScreenRecord(
    id: 'GIF-001',
    name: 'Entry',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-002',
    name: 'Relationship',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-003',
    name: 'Occasion',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-004',
    name: 'Story',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-005',
    name: 'Interests',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-006',
    name: 'Recipient',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-007',
    name: 'Budget',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-008',
    name: 'IRIS',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-009',
    name: 'Review',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-010',
    name: 'Payment',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'GIF-011',
    name: 'Gift Story',
    product: DesignInventoryProduct.gifts,
    status: DesignInventoryStatus.inProgress,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.inProgress,
    deployment: DesignInventoryStatus.uiPending,
    missingWork: ['recipient web story QA', 'deployment'],
  ),
];

const financeScreenRegistry = <DesignScreenRecord>[
  DesignScreenRecord(
    id: 'FIN-001',
    name: 'Wallet',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.deployed,
    stateIds: [
      'FIN-001-ST-01',
      'FIN-001-ST-02',
      'FIN-001-ST-03',
      'FIN-001-ST-04',
      'FIN-001-ST-05',
      'FIN-001-ST-06',
    ],
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'FIN-002',
    name: 'Pay With',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'FIN-003',
    name: 'Available Roth',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'FIN-004',
    name: 'Recent Activity',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'FIN-005',
    name: 'Referral Rewards',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'FIN-006',
    name: 'Roth Cards',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.uiPending,
    backend: DesignInventoryStatus.backendOnly,
    ui: DesignInventoryStatus.uiPending,
    deployment: DesignInventoryStatus.uiPending,
    missingWork: ['production Roth Card management UI'],
  ),
  DesignScreenRecord(
    id: 'FIN-007',
    name: 'Offers',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.deployed,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'FIN-008',
    name: 'Payment Profile',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'FIN-009',
    name: 'Checkout',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.implemented,
    backend: DesignInventoryStatus.implemented,
    ui: DesignInventoryStatus.implemented,
    deployment: DesignInventoryStatus.deployed,
  ),
  DesignScreenRecord(
    id: 'FIN-010',
    name: 'Rider Earnings',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.uiPending,
    backend: DesignInventoryStatus.backendOnly,
    ui: DesignInventoryStatus.uiPending,
    deployment: DesignInventoryStatus.uiPending,
    missingWork: ['Rider Earnings product build'],
  ),
  DesignScreenRecord(
    id: 'FIN-011',
    name: 'Business Finance',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.uiPending,
    backend: DesignInventoryStatus.backendOnly,
    ui: DesignInventoryStatus.uiPending,
    deployment: DesignInventoryStatus.uiPending,
    missingWork: ['Business Finance product build'],
  ),
  DesignScreenRecord(
    id: 'FIN-012',
    name: 'Admin Finance',
    product: DesignInventoryProduct.finance,
    status: DesignInventoryStatus.uiPending,
    backend: DesignInventoryStatus.backendOnly,
    ui: DesignInventoryStatus.uiPending,
    deployment: DesignInventoryStatus.uiPending,
    missingWork: ['Admin Finance product build'],
  ),
];

const screenRegistry = <DesignScreenRecord>[
  ...senderScreenRegistry,
  ...riderScreenRegistry,
  ...healthScreenRegistry,
  ...giftsScreenRegistry,
  ...financeScreenRegistry,
];
